services:
  - type: web
    name: movielens-api
    env: python
    plan: free
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
